name: 🐛 Bug报告 / Bug Report
description: 报告Magic中的bug或异常行为
title: "[Bug]: "
labels: ["bug", "needs-triage", "zh-cn"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间报告bug！请尽可能完整地填写此表单。
        
        **提交bug报告前，请先：**
        - 检查是否已在[现有issues](https://github.com/dtyq/magic/issues)中报告过此问题
        - 阅读我们的[文档](https://docs.letsmagic.cn/zh)
        - 尝试使用最新版本重现问题

  - type: dropdown
    id: component
    attributes:
      label: 组件模块
      description: 哪个组件/模块受到影响？
      options:
        - Super Magic (超级麦吉)
        - Magic IM (聊天模块)
        - Magic Flow (AI 工作流)
        - Magic Service (后端API)
        - Magic Web (前端)
        - Magic Gateway (网关)
        - 文档
        - 部署/安装
        - 其他
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: 部署方式
      description: 您是如何运行Magic的？
      options:
        - 自托管 (Docker)
        - 自托管 (源码)
        - 云服务
        - 开发环境
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug描述
      description: 清楚简洁地描述bug是什么
      placeholder: 描述发生了什么以及您期望发生什么
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 重现步骤
      description: 详细描述重现该行为的步骤
      placeholder: |
        1. 进入 '...'
        2. 点击 '...'
        3. 向下滚动到 '...'
        4. 看到错误
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望行为
      description: 清楚简洁地描述您期望发生什么
      placeholder: 应该发生什么？
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 实际发生了什么？
      placeholder: 描述实际行为或错误消息
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      description: 请提供环境详细信息
      placeholder: |
        - 操作系统：[如 macOS 14.0, Ubuntu 22.04, Windows 11]
        - Docker版本：[如 24.0.7]
        - Magic版本：[如 v1.0.0]
        - 浏览器：[如 Chrome 119.0, Safari 17.0]（如果是前端相关）
        - 模型提供商：[如 OpenAI GPT-4, Claude, 本地LLM]（如果是AI相关）
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 日志和错误消息
      description: 请包含相关的日志、错误消息或截图
      placeholder: |
        ```
        在此粘贴日志...
        ```
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 在此添加有关问题的任何其他信息
      placeholder: 任何可能帮助我们理解问题的额外信息
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 请确认以下事项
      options:
        - label: 我已经在创建此报告前搜索了现有issues
          required: true
        - label: 我已经提供了上述所有必需信息
          required: true
        - label: 此问题是可重现的
          required: true 