name: ✨ 功能请求 / Feature Request
description: 为Magic建议新功能或改进
title: "[功能]: "
labels: ["enhancement", "needs-review", "zh-cn"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间建议新功能！我们重视社区在塑造Magic未来中的意见。
        
        **提交功能请求前，请先：**
        - 检查是否已在[现有issues](https://github.com/dtyq/magic/issues)中请求过此功能
        - 查看我们的[路线图](https://github.com/dtyq/magic/discussions)（如果有）
        - 考虑此功能是否符合Magic的核心理念

  - type: dropdown
    id: component
    attributes:
      label: 组件模块
      description: 此功能会影响哪个组件/模块？
      options:
        - Super Magic (AI智能体)
        - Magic IM (聊天系统)
        - Magic Flow (工作流系统)
        - Magic Service (后端API)
        - Magic Web (前端界面)
        - Magic Gateway (网关)
        - Agentlang框架
        - 文档
        - 部署/安装
        - 开发者体验
        - 其他
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型
      description: 这是什么类型的功能？
      options:
        - 全新功能
        - 现有功能增强
        - 性能改进
        - 开发者体验改进
        - API增强
        - UI/UX改进
        - 外部服务集成
        - 安全增强
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 问题描述
      description: 您的功能请求是否与某个问题相关？请描述痛点。
      placeholder: 清楚简洁地描述问题是什么。例如：我总是在[某种情况下]感到困扰...
    validations:
      required: false

  - type: textarea
    id: solution-description
    attributes:
      label: 建议方案
      description: 描述您希望看到实现的解决方案
      placeholder: 清楚简洁地描述您希望发生什么
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 使用场景
      description: 描述此功能有价值的具体使用场景
      placeholder: |
        1. 作为[用户类型]，我想要[操作]，这样[好处]
        2. 当[场景]时，此功能将通过[好处]提供帮助
        3. ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 描述您考虑过的任何替代解决方案或功能
      placeholder: 您还考虑过哪些其他方法？为什么这个解决方案会更好？
    validations:
      required: false

  - type: textarea
    id: implementation-suggestions
    attributes:
      label: 实现建议
      description: 如果您对如何实现有想法，请分享
      placeholder: |
        - 技术方法建议
        - API设计想法
        - UI/UX模型或描述
        - 集成点
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 此功能对您/您的用例有多重要？
      options:
        - 低 - 有了更好
        - 中 - 会有帮助
        - 高 - 对我的用例很重要
        - 关键 - 阻碍我的用例
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: 用户类型
      description: 什么类型的用户会从此功能中受益？
      options:
        - 终端用户（使用Magic产品）
        - 开发者（集成/扩展Magic）
        - 系统管理员
        - 企业/团队管理员
        - 所有用户
        - 其他
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加有关功能请求的任何其他信息、截图、模型或示例
      placeholder: |
        - 截图或模型
        - 其他工具中类似功能的链接
        - 其他技术细节
        - 业务影响或指标
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 请确认以下事项
      options:
        - label: 我已经在创建此请求前搜索了现有功能请求
          required: true
        - label: 我已经提供了对建议功能的清楚描述
          required: true
        - label: 我理解这是一个请求，可能不会立即实现
          required: true 