name: 📚 文档问题 / Documentation
description: 报告文档问题或建议改进
title: "[文档]: "
labels: ["documentation", "needs-review", "zh-cn"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您帮助改进Magic的文档！清晰的文档对项目成功至关重要。
        
        **提交文档问题前，请先：**
        - 检查是否已经报告过此文档问题
        - 浏览我们当前的[文档](https://docs.letsmagic.cn/zh)
        - 考虑您的建议是否对其他用户有帮助

  - type: dropdown
    id: doc-type
    attributes:
      label: 文档类型
      description: 这是什么类型的文档问题？
      options:
        - 缺少文档
        - 信息错误/过时
        - 解释不清楚
        - API文档
        - 教程/指南改进
        - 代码示例
        - 安装/设置指南
        - 故障排除指南
        - 翻译问题
        - 其他
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 组件模块
      description: 此文档与哪个组件/模块相关？
      options:
        - Super Magic (AI智能体)
        - Magic IM (聊天系统)
        - Magic Flow (工作流系统)
        - Magic Service (后端API)
        - Magic Web (前端界面)
        - Magic Gateway (网关)
        - Agentlang框架
        - 安装/部署
        - 快速开始
        - API参考
        - 开发者指南
        - 总览/概述
        - 其他
    validations:
      required: true

  - type: input
    id: doc-url
    attributes:
      label: 文档URL
      description: 如果适用，请提供文档页面的URL
      placeholder: https://docs.letsmagic.cn/zh/...
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: 问题描述
      description: 描述需要改进的文档问题
      placeholder: |
        - 缺少什么、不正确或不清楚的地方？
        - 应该添加或更正什么具体信息？
        - 这如何影响用户理解？
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: 当前内容（如适用）
      description: 引用需要改进的当前文档内容
      placeholder: |
        ```
        当前文档内容...
        ```
    validations:
      required: false

  - type: textarea
    id: suggested-content
    attributes:
      label: 建议内容
      description: 提供您建议的内容或改进
      placeholder: |
        您建议的文档内容或改进...
    validations:
      required: false

  - type: dropdown
    id: target-audience
    attributes:
      label: 目标受众
      description: 此文档的主要受众是谁？
      options:
        - 初学者/新用户
        - 中级用户
        - 高级用户
        - 开发者/集成商
        - 系统管理员
        - 所有用户
        - 其他
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 此文档改进有多重要？
      options:
        - 低 - 小改进
        - 中 - 有用的补充
        - 高 - 对用户体验重要
        - 关键 - 阻碍用户成功
    validations:
      required: true

  - type: textarea
    id: user-impact
    attributes:
      label: 用户影响
      description: 此文档改进将如何帮助用户？
      placeholder: |
        - 这将为用户解决什么问题？
        - 哪些用户场景会受益？
        - 这将如何改善整体用户体验？
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加任何其他相关信息、截图或示例
      placeholder: |
        - 令人困惑的UI截图
        - 其他项目做得好的示例
        - 相关讨论链接
        - 应该记录的技术细节
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 请确认以下事项
      options:
        - label: 我已经在创建此问题前搜索了现有文档问题
          required: true
        - label: 我已经提供了关于所需文档改进的具体细节
          required: true
        - label: 我理解文档改进有助于整个社区
          required: true 