name: ⚡ 性能问题 / Performance Issue
description: 报告性能问题或建议优化
title: "[性能]: "
labels: ["performance", "needs-investigation", "zh-cn"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您帮助我们识别性能问题！性能对于良好的用户体验至关重要。
        
        **提交性能问题前，请先：**
        - 尝试多次重现该问题
        - 检查最新版本是否仍然存在此问题
        - 考虑这是否可能与您的特定环境或配置有关

  - type: dropdown
    id: component
    attributes:
      label: 组件模块
      description: 哪个组件/模块遇到性能问题？
      options:
        - Super Magic (AI智能体)
        - Magic IM (聊天系统)
        - Magic Flow (工作流系统)
        - Magic Service (后端API)
        - Magic Web (前端界面)
        - Magic Gateway (网关)
        - 数据库查询
        - 文件操作
        - 网络/API调用
        - AI模型推理
        - 内存使用
        - 其他
    validations:
      required: true

  - type: dropdown
    id: performance-type
    attributes:
      label: 性能问题类型
      description: 您遇到的是什么类型的性能问题？
      options:
        - 响应时间慢
        - 内存使用率高
        - CPU使用率高
        - 数据库查询性能
        - 前端渲染/加载
        - API端点性能
        - 文件上传/下载速度
        - AI模型响应时间
        - 工作流执行时间
        - 其他
    validations:
      required: true

  - type: textarea
    id: performance-description
    attributes:
      label: 性能问题描述
      description: 描述您遇到的性能问题
      placeholder: |
        - 哪个具体操作或功能运行缓慢？
        - 您何时首次注意到此问题？
        - 这种情况发生的频率如何？
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: 期望性能
      description: 您对此操作期望的性能是什么？
      placeholder: |
        - 期望的响应时间
        - 期望的资源使用情况
        - 期望的行为
    validations:
      required: true

  - type: textarea
    id: actual-performance
    attributes:
      label: 实际性能
      description: 您实际遇到的性能是什么？
      placeholder: |
        - 实际响应时间（如：5-10秒）
        - 实际资源使用情况（如：80% CPU，2GB RAM）
        - 任何错误消息或超时
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 重现步骤
      description: 重现性能问题的详细步骤
      placeholder: |
        1. 进入 '...'
        2. 执行操作 '...'
        3. 等待响应
        4. 观察到缓慢性能
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 环境详情
      description: 请提供详细的环境信息
      placeholder: |
        - 操作系统：[如 macOS 14.0, Ubuntu 22.04, Windows 11]
        - 硬件：[如 CPU, RAM, 存储类型]
        - Docker版本：[如 24.0.7]
        - Magic版本：[如 v1.0.0]
        - 部署方式：[如 Docker Compose, K8s, 本地]
        - 数据库：[如 MySQL 8.0, PostgreSQL 15]
        - 模型提供商：[如 OpenAI GPT-4, Claude, 本地LLM]
        - 网络：[如 本地网络, 云部署]
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: 性能指标
      description: 如果您有任何性能指标，请分享
      placeholder: |
        - 响应时间（平均、最小、最大）
        - 资源使用情况（CPU、内存、磁盘I/O）
        - 请求速率或吞吐量
        - 错误率
        - 任何监控数据或日志
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: 配置详情
      description: 请分享可能影响性能的相关配置
      placeholder: |
        - 相关环境变量
        - 数据库配置
        - 资源限制/分配
        - 模型设置（如果与AI相关）
        - 工作流复杂度（如果与Flow相关）
    validations:
      required: false

  - type: dropdown
    id: data-size
    attributes:
      label: 数据/负载大小
      description: 问题发生时数据或负载的大概大小？
      options:
        - 小（< 1MB，< 100条记录）
        - 中（1-100MB，100-1万条记录）
        - 大（100MB-1GB，1万-100万条记录）
        - 非常大（> 1GB，> 100万条记录）
        - 不适用
        - 未知
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: 严重程度
      description: 此性能问题有多严重？
      options:
        - 低 - 轻微不便
        - 中 - 明显延迟
        - 高 - 严重影响可用性
        - 关键 - 导致功能无法使用
    validations:
      required: true

  - type: textarea
    id: workarounds
    attributes:
      label: 解决方法
      description: 您是否找到了此性能问题的任何解决方法？
      placeholder: 您尝试过的任何临时解决方案或优化
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加有关性能问题的任何其他信息
      placeholder: |
        - 性能监控截图
        - 显示慢操作的日志
        - 与期望行为的比较
        - 相关问题或模式
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 请确认以下事项
      options:
        - label: 我已经在创建此报告前搜索了现有性能问题
          required: true
        - label: 我已经提供了详细的性能指标和环境信息
          required: true
        - label: 我已经尝试多次重现此问题
          required: true 