name: 🚀 部署/安装问题 / Deployment Issue
description: 报告部署、安装或设置问题
title: "[部署]: "
labels: ["deployment", "installation", "setup", "zh-cn"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您报告部署或安装问题！这有助于我们改进Magic的设置体验。
        
        **提交部署问题前，请先：**
        - 检查[安装文档](https://docs.letsmagic.cn/zh)
        - 验证系统要求是否满足
        - 如果可能，在干净环境中尝试安装步骤

  - type: dropdown
    id: deployment-type
    attributes:
      label: 部署类型
      description: 您尝试的是什么类型的部署？
      options:
        - Docker Compose（推荐）
        - 源码安装
        - Kubernetes
        - 云部署（AWS/GCP/Azure）
        - 本地开发环境设置
        - 生产环境部署
        - 更新/升级过程
        - 其他
    validations:
      required: true

  - type: dropdown
    id: installation-stage
    attributes:
      label: 安装阶段
      description: 您在哪个阶段遇到问题？
      options:
        - 系统要求检查
        - 初始设置/克隆
        - 环境配置
        - Docker容器启动
        - 数据库初始化
        - 服务启动
        - 首次访问
        - 配置验证
        - 服务集成
        - 安装后测试
        - 其他
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: 问题描述
      description: 描述您遇到的部署/安装问题
      placeholder: |
        - 哪个具体步骤失败了？
        - 您看到什么错误消息？
        - 这在过程中何时发生？
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 重现步骤
      description: 您遵循的导致问题的详细步骤
      placeholder: |
        1. 从[来源]下载Magic
        2. 运行命令：[命令]
        3. 配置[组件]
        4. 观察错误：[错误]
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 环境详情
      description: 请提供详细的环境信息
      placeholder: |
        - 操作系统：[如 macOS 14.0, Ubuntu 22.04, Windows 11]
        - 架构：[如 x86_64, arm64/M1]
        - Docker版本：[如 24.0.7]
        - Docker Compose版本：[如 2.21.0]
        - 可用内存：[如 16GB]
        - 可用磁盘空间：[如 100GB]
        - 网络配置：[如 企业防火墙, 代理]
        - Magic版本：[如 v1.0.0, latest, commit hash]
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: 配置详情
      description: 分享您的配置（请隐藏敏感信息）
      placeholder: |
        环境变量（.env文件）：
        ```
        MAGIC_API_URL=http://localhost:9501
        DATABASE_HOST=mysql
        # [其他相关配置 - 请隐藏API密钥和密码]
        ```
        
        Docker Compose覆盖：
        ```yaml
        # 任何自定义docker-compose配置
        ```
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: 错误日志
      description: 包含相关错误日志、堆栈跟踪或错误消息
      placeholder: |
        ```
        [时间戳] ERROR: 容器启动失败
        [时间戳] STDERR: 访问/var/lib/magic权限被拒绝
        [时间戳] EXIT CODE: 1
        ```
    validations:
      required: true

  - type: textarea
    id: system-status
    attributes:
      label: 系统状态
      description: 提供相关系统状态命令的输出
      placeholder: |
        Docker状态：
        ```bash
        $ docker --version
        $ docker-compose --version
        $ docker ps
        $ docker logs magic-service
        ```
        
        系统资源：
        ```bash
        $ df -h
        $ free -h
        $ ulimit -a
        ```
    validations:
      required: false

  - type: dropdown
    id: first-time
    attributes:
      label: 安装类型
      description: 这是您第一次安装Magic吗？
      options:
        - 首次安装
        - 之前成功后的重新安装
        - 从之前版本更新
        - 从不同设置迁移
        - 尝试不同的部署方法
    validations:
      required: true

  - type: textarea
    id: previous-attempts
    attributes:
      label: 之前的尝试
      description: 您是否尝试过任何故障排除步骤或替代方法？
      placeholder: |
        - 清除了Docker卷并重新启动
        - 尝试了不同的Magic版本
        - 更改了环境变量
        - 检查了防火墙设置
        - [其他故障排除步骤]
    validations:
      required: false

  - type: dropdown
    id: blocking-severity
    attributes:
      label: 严重程度
      description: 这对您的阻碍有多大？
      options:
        - 关键 - 完全无法使用Magic
        - 高 - 主要功能无法工作
        - 中 - 某些功能无法工作
        - 低 - 轻微不便
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: 期望结果
      description: 安装/部署成功时应该发生什么？
      placeholder: |
        - 所有服务应该成功启动
        - Web界面应该可以在http://localhost:8080访问
        - API应该在http://localhost:9501响应
        - 应该能够创建第一个用户账户
    validations:
      required: true

  - type: textarea
    id: workarounds
    attributes:
      label: 解决方法
      description: 您是否找到了任何临时解决方法？
      placeholder: 任何允许您继续的临时解决方案
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加任何其他相关信息
      placeholder: |
        - 错误消息截图
        - 网络拓扑详情
        - 影响安装的企业安全策略
        - 之前成功的安装
        - 与工作环境的比较
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 请确认以下事项
      options:
        - label: 我已阅读安装文档
          required: true
        - label: 我已验证我的系统满足最低要求
          required: true
        - label: 我已提供完整的错误日志和环境详情
          required: true
        - label: 我已从报告中隐藏任何敏感信息
          required: true 